// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmbyj0fGiEM-tVbOb_GPJC_7dHEp_0Fw',
    appId: '1:144031282317:web:c45bf00188a30e888b1ec4',
    messagingSenderId: '144031282317',
    projectId: 'crud-n2-mobile',
    authDomain: 'crud-n2-mobile.firebaseapp.com',
    storageBucket: 'crud-n2-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADhseupbTdrNkQOwcR-5_7KxAoQeVBLpY',
    appId: '1:144031282317:android:fe8f6b3d84865ced8b1ec4',
    messagingSenderId: '144031282317',
    projectId: 'crud-n2-mobile',
    storageBucket: 'crud-n2-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC324s0ZLl1twZhBm9B2689BuNr6MO-JnA',
    appId: '1:144031282317:ios:3da94372333197148b1ec4',
    messagingSenderId: '144031282317',
    projectId: 'crud-n2-mobile',
    storageBucket: 'crud-n2-mobile.appspot.com',
    iosBundleId: 'com.example.crudN2Mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC324s0ZLl1twZhBm9B2689BuNr6MO-JnA',
    appId: '1:144031282317:ios:465f9b6ff493247f8b1ec4',
    messagingSenderId: '144031282317',
    projectId: 'crud-n2-mobile',
    storageBucket: 'crud-n2-mobile.appspot.com',
    iosBundleId: 'com.example.crudN2Mobile.RunnerTests',
  );
}
